/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedEdicaoRouteImport } from './routes/_authenticated/edicao'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMesarioRouteImport } from './routes/_authenticated/mesario'
import { Route as AuthenticatedSumulaMatchIdRouteImport } from './routes/_authenticated/sumula.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEdicaoRoute = AuthenticatedEdicaoRouteImport.update({
  id: '/edicao',
  path: '/edicao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesarioRoute = AuthenticatedMesarioRouteImport.update({
  id: '/mesario',
  path: '/mesario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSumulaMatchIdRoute =
  AuthenticatedSumulaMatchIdRouteImport.update({
    id: '/sumula/$matchId',
    path: '/sumula/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classificacao': typeof ClassificacaoRoute
  '/rankings': typeof RankingsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conta': typeof AuthenticatedContaRoute
  '/edicao': typeof AuthenticatedEdicaoRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/mesario': typeof AuthenticatedMesarioRoute
  '/sumula/$matchId': typeof AuthenticatedSumulaMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classificacao': typeof ClassificacaoRoute
  '/rankings': typeof RankingsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conta': typeof AuthenticatedContaRoute
  '/edicao': typeof AuthenticatedEdicaoRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/mesario': typeof AuthenticatedMesarioRoute
  '/sumula/$matchId': typeof AuthenticatedSumulaMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/classificacao': typeof ClassificacaoRoute
  '/rankings': typeof RankingsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/edicao': typeof AuthenticatedEdicaoRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/mesario': typeof AuthenticatedMesarioRoute
  '/_authenticated/sumula/$matchId': typeof AuthenticatedSumulaMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classificacao'
    | '/rankings'
    | '/admin'
    | '/conta'
    | '/edicao'
    | '/marketing'
    | '/mesario'
    | '/sumula/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/classificacao'
    | '/rankings'
    | '/admin'
    | '/conta'
    | '/edicao'
    | '/marketing'
    | '/mesario'
    | '/sumula/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/classificacao'
    | '/rankings'
    | '/_authenticated/admin'
    | '/_authenticated/conta'
    | '/_authenticated/edicao'
    | '/_authenticated/marketing'
    | '/_authenticated/mesario'
    | '/_authenticated/sumula/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  RankingsRoute: typeof RankingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edicao': {
      id: '/_authenticated/edicao'
      path: '/edicao'
      fullPath: '/edicao'
      preLoaderRoute: typeof AuthenticatedEdicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesario': {
      id: '/_authenticated/mesario'
      path: '/mesario'
      fullPath: '/mesario'
      preLoaderRoute: typeof AuthenticatedMesarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sumula/$matchId': {
      id: '/_authenticated/sumula/$matchId'
      path: '/sumula/$matchId'
      fullPath: '/sumula/$matchId'
      preLoaderRoute: typeof AuthenticatedSumulaMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedEdicaoRoute: typeof AuthenticatedEdicaoRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMesarioRoute: typeof AuthenticatedMesarioRoute
  AuthenticatedSumulaMatchIdRoute: typeof AuthenticatedSumulaMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedEdicaoRoute: AuthenticatedEdicaoRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMesarioRoute: AuthenticatedMesarioRoute,
  AuthenticatedSumulaMatchIdRoute: AuthenticatedSumulaMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  RankingsRoute: RankingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
